import = ["/home/ezra/.config/alacritty/mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MartianMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MartianMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MartianMono Nerd Font"
style = "Italic"

[font.normal]
family = "MartianMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
startup_mode = "Maximized"
opacity = 0.9
decorations = "None"

[window.padding]
x = 20
y = 20
