
[env]
TERM = "xterm-256color"

[window]
padding = {x = 20, y = 25}
dynamic_padding = true
opacity = 0.8
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "MartianMono Nerd Font", style = "Regular" }
bold = { family = "MartianMono Nerd Font", style = "Bold" }
italic = { family = "MartianMono Nerd Font", style = "Italic" }
bold_italic = { family = "MartianMono Nerd Font", style = "Bold Italic" }
size = 12.0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
style = { shape = "Block", blinking = "Always" }

[general]
import = ["/home/ezra/.config/alacritty/gruvbox-dark.toml"]

