set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Base index
set -g base-index 1

# Remap prefix key
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Start with pane 1
set -g pane-base-index 1

# Source config file
bind r source-file ~/.config/tmux/tmux.conf

# Use vi mode
setw -g mode-keys vi
set -g status-keys vi
# setw -g utf8 on

# Use mouse in copy mode
# setw -g mode-mouse off
set-window-option -g mode-keys vi
# Moving between panes with vim movement keys
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Easy-to-remember split pane commands
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

